version: "3.8"

services:
  user-ms:
    build: MS-User
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=$DATABASE_URL
  team-ms:
    build: MS-Team
    ports:
      - "8085:8085"
    environment:
      - MONGO_URL=$MONGO_URL
  discovery-service:
    build: EdgeMS
    ports:
      - "8761:8761"
  gateway:
    build: gateway
    ports:
      - "8222:8222"